name: Rust

on:
  push:
    branches: [ master ]
    tags: v*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build binaries release
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
